const menu = [
  {
    id: 1,
    title: "Pancakes",
    category: "breakfast",
    price: 18.99,
    img: "./Components/Cards/Images/1.jpg",
    desc: `I am a pancake`,
  },
  {
    id: 2,
    title: "Pizza",
    category: "lunch",
    price: 21.99,
    img: "./Components/Cards/Images/2.jpg",
    desc: `I am a pizza`,
  },
  {
    id: 3,
    title: "Milkshake",
    category: "shakes",
    price: 12.99,
    img: "./Components/Cards/Images/3.jpg",
    desc: `I am a milkshake`,
  },
  {
    id: 4,
    title: "Croissant",
    category: "breakfast",
    price: 14.99,
    img: "./Components/Cards/Images/4.jpg",
    desc: `I am a croissant`,
  },
  {
    id: 5,
    title: "Pasta",
    category: "lunch",
    price: 22.99,
    img: "./Components/Cards/Images/5.jpg",
    desc: `I am a pasta`,
  },
  {
    id: 6,
    title: "Biscoff Shake",
    category: "shakes",
    price: 18.99,
    img: "./Components/Cards/Images/6.jpg",
    desc: `I am a shake`,
  },
  {
    id: 7,
    title: "Sandwich",
    category: "breakfast",
    price: 8.99,
    img: "./Components/Cards/Images/7.jpg",
    desc: `I am a sandwich`,
  },
  {
    id: 8,
    title: "Burrito",
    category: "lunch",
    price: 12.99,
    img: "./Components/Cards/Images/8.jpg",
    desc: `I am a burrito`,
  },
  {
    id: 9,
    title: "Oreo Shake",
    category: "shakes",
    price: 19.99,
    img: "./Components/Cards/Images/9.jpg",
    desc: `I am a oreo shake`,
  },
];
export default menu;
